language: node_js
sudo: required
dist: trusty

node_js:
  - 6
  - 7

env:
  - TEST_CLIENT_DIR=client

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: cd $TEST_CLIENT_DIR && npm install && npm run ci

language: go

go:
  - 1.x
  - 1.7
  - 1.8
  - 1.9

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

install:
- go get -t ./...

script:
- go test -v ./..
