version: '2.1'

services:
    frontend:
        image: frontend
        ports:
            - "80:80"
            - "443:443"
    
    db:
        image: postgres
        environment:
            POSTGRES_USER: pf
            POSTGRES_PASSWORD: patientfocus
            POSTGRES_DB: patientfocus
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 10s
            retries: 3
        volumes:
            - ./postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    backend:
        image: backend
        ports:
            - "9000:9000"
        environment:
            POSTGRES_USER: pf
            POSTGRES_PASSWORD: patientfocus
            POSTGRES_DB: patientfocus
            POSTGRES_HOST: 192.168.0.106
        volumes:
            - ./files:/var/www/patientfocus
        depends_on:
            db:
                condition: service_healthy
        links:
            - db:db
    