version: '2.1'

services:
    frontend:
        image: frontend
        ports:
            - "80:80"
            - "443:443"
    backend:
        image: backend
        ports:
            - "9000:9000"
        environment:
            POSTGRES_USER: pf
            POSTGRES_PASSWORD: patientfocus
            POSTGRES_DB: patientfocus
            POSTGRES_HOST: 172.31.9.111
    
