version: '3.1'

services:
    backend:
        image: backend
        ports:
            - "9000:9000"
        depends_on:
            - "db"

    db:
        image: postgres
        environment:
            POSTGRES_DB: patientfocus
            POSTGRES_USER: pf
            POSTGRES_PASSWORD: patientfocus
        volumes:
            - /Users/i861632/Develop/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
