version: '3.1'

services:

    db:
        image: postgres
        environment:
            POSTGRES_USER: pf
            POSTGRES_PASSWORD: patientfocus
            POSTGRES_DB: patientfocus
        volumes:
            - /home/george/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
