version: '3.1'

services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: user
            POSTGRES_USER: pf
            POSTGRES_PASSWORD: patientfocus
        volumes:
            - /home/cyap/work/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    backend:
        image: backend
        ports:
            - "80:9000"
